# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'DevPaySDKSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'DevPaySDK',:path=>'./../'
  # Pods for DevPaySDKSample

end
